### ISSUE TITLE
Select field can't be unselected if 0 is also an option

### ISSUE THREAD

**Issue by adamcapriola** [WebDevStudios/CMB2#115]
I want to have a select field that is unselected by default with options than have integer values. In this scenario, the unselected option can't be chosen when 0 is the name/value of one of the options. (By default 0 is always selected.) Removing the 0 option allows for the unselected option.

EDIT: Actually, I think the problem might be that I can't seem to save a value of 0 (zero). It is being treated the same as null, false, and '' from what I can tell.

Metabox:

``` php
add_filter( 'cmb2_meta_boxes', 'ac_metaboxes' );

function ac_metaboxes( array $meta_boxes ) {

    $meta_boxes['my_metabox'] = array(
        'id'            => 'my_metabox',
        'title'         => 'My Title',
        'object_types'  => array( 'post' ),
        'context'       => 'normal',
        'priority'      => 'high',
        'show_names'    => true,
        'fields'        => array(
            array(
                'name' => 'My Field',
                'id'   => 'my_field',
                'type' => 'select',
                'options' => array(
                    ''   => '',
                    '0'  => '0',
                    '1'  => '1',
                    '2'  => '2'
                )
            )
        )
    );

}
```

WordPress version: 4.0.1
CMB2 version: 2.0.0.3

**Comment by inspiraaz** [comment]
I'm having the same problem, is there any solution for this ?

WordPress 4.1
CMB2 v2.0.0.9

**Comment by jtsternberg** [comment]
I think this issue has been resolved. Can you please update your copy of CMB2 and verify?

**Comment by adamcapriola** [comment]
Very late response ... but I am still having this issue. `0` is selected by default and I can't save the no value option.

**Comment by tw2113** [comment]
Can someone re-test with the latest version of trunk, please?

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
