### ISSUE TITLE
Repeatable Select within a Repeatable Group Issue

### ISSUE THREAD

**Issue by Blindmikey** [WebDevStudios/CMB2#148]
Wordpress Version: 4.1
CMB2 Version: Master (1/16/2015)

Create a Repeatable Group, within add a repeatable select field. On page submission, after page reload you'll find additional select fields (rows) that you had not intentionally created. 

https://gist.github.com/Blindmikey/bfd53603fdb2655f796c

**Comment by Blindmikey** [comment]
Looks to be a mirror of: 
https://github.com/WebDevStudios/CMB2/issues/116

**Comment by Blindmikey** [comment]
However, these are not custom fields. Not sure if I'm going about this wrong, some eyes would still be appreciated, so I'm opening this.

**Comment by victorpetryk** [comment]
Same Issue. I have created repeatable Text field, and when Post is updated, it generated one text field with "Array" value. And so the circle, at each update Post generated another field.

**Comment by buniden** [comment]
I'm having this problem as well.  Is this a bug or a set up issue?

**Comment by jtsternberg** [comment]
@victorpetryk @buniden are you having this issue with a repeatable text field within in repeatable group?

**Comment by jtsternberg** [comment]
I fixed a few bugs, which I think will help you guys out. Please update and let me know.

**Comment by Blindmikey** [comment]
Thanks for the updates!

I'm still having an issue with an extra select field showing upon save however.

My tasks to recreate:
1. create repeatable group
2. within that group create a repeatable select dropdown
3. fill out repeatable form w/repeatable select dropdown in wp-admin & save post
4. you'll find an additional select dropdown that you hadn't created

**Comment by buniden** [comment]
That fixed the issue for me.  I'm using a repeatable text field in an options page with a custom sanitization_cb to remove the backslashes.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
