### ISSUE TITLE
User Profile metaboxes not updating on save. 

### ISSUE THREAD

**Issue by katielacy** [WebDevStudios/CMB2#160]
Hey Guys, 

Love this plugin such a time saver!

I have a issue with the user profile. When I update the fields are not be validated. Very strange! Could you please help I am using your latest version on CMB2 and wordpress 4.1

Here is my code ....

```php
function cmb2_user_metabox( array $meta_boxes ) {
$args2 = array( 'post_type' => 'int_contacts', 'posts_per_page' => 100 ,
    'tax_query' => array(
		array(
			'taxonomy' => 'section',
			'field'    => 'slug',
			'terms'    => 'depot',
		),
	), );
$loop = new WP_Query( $args2 );
$depot = array();
while ( $loop->have_posts() ) : $loop->the_post();
 global $post;
 $depot[$post->ID] = get_the_title();
endwhile;
    // Start with an underscore to hide fields from custom fields list
    $prefix = '_eko_';

    /**
     * Sample metabox to demonstrate each field type included
     */
    $meta_boxes['user_metabox'] = array(
        'id'               => 'user_edit',
		'title'            => __( 'User Profile Metabox', 'cmb2' ),
		'object_types'     => array( 'user' ), // Tells CMB to use user_meta vs post_meta
		'show_names'       => true,
		'new_user_section' => 'add-new-user', // where form will show on new user page. 'add-existing-user' is only other valid option.
		'fields'           => array(
           array(
                'name' => 'Adler and Allan Company Information',
                'desc' => 'Please enter your information below',
                'type' => 'title',
                'id'   => $prefix . 'adler_information'
            ),
            array(
                'name'    => 'Unique Employee Number',
                'desc'    => '',
                'default' => '',
                'id'      => $prefix . 'employee_number',
                'type'    => 'text'
            ),
            array(
                'name'    => 'GMEE Record ID',
                'desc'    => '',
                'default' => '',
                'id'      => $prefix . 'gmee_number',
                'type'    => 'text'
            ),
            array(
                'name'    => 'Depot',
                'desc'    => '',
                'default' => '',
                'id'      => $prefix . 'depot',
                'type' => 'pw_select',
                'sanitization_cb' => 'pw_select2_sanitise',
                'options' => $depot,
            ),
            array(
                'name'    => 'Divison',
                'desc'    => '',
                'default' => '',
                'id'      => $prefix . 'divison',
                'type'    => 'text'
            ),
            array(
                'name'    => 'Group Email',
                'desc'    => '',
                'default' => '',
                'id'      => $prefix . 'group_email',
                'type'    => 'text_email'
            ),
            
          ),
   );

    // Add other metaboxes as needed

    return $meta_boxes;
}
```

**Comment by jtsternberg** [comment]
Can you please be more specific? Are you referring to the fields using the 'sanitization_cb' parameter? if so, you'll need to post your code for the callback function `pw_select2_sanitise`, as well. Also, keep in mind, this is not validation, but sanitization. It will not keep the form from submitting, but clean the values after the form is submitted.

**Comment by katielacy** [comment]
I am referring to the sanitisation the fields are not updating when clicking update user. I am using your fields not my own. I have tried this without the select2 type along with removing the loop above. 

I have also tried just using a text box and still no luck.

**Comment by jtsternberg** [comment]
Using your code (slightly modified) works for me. screenshot: http://b.ustin.co/13MHH
I doubt it is the issue, but please also update CMB2 as I pushed out an update this morning.

my code:
```php
<?php
add_filter( 'cmb2_meta_boxes', 'cmb2_user_metabox_test' );
function cmb2_user_metabox_test( array $meta_boxes ) {

	$args2 = array(
		'post_type' => 'post',
		'posts_per_page' => 5,
	);
	$loop = get_posts( $args2 );

	$depot = array();
	foreach ( $loop as $_post ) {
		$depot[ $_post->ID ] = $_post->post_title;
	}

	// Start with an underscore to hide fields from custom fields list
	$prefix = '_eko_';

	/**
	 * Sample metabox to demonstrate each field type included
	 */
	$meta_boxes['user_metabox'] = array(
			'id' => 'user_edit',
			'title' => __( 'User Profile Metabox', 'cmb2' ),
			'object_types'     => array( 'user' ), // Tells CMB to use user_meta vs post_meta
			'show_names'       => true,
			'new_user_section' => 'add-new-user', // where form will show on new user page. 'add-existing-user' is only other valid option.
			'fields'           => array(
				array(
					'name' => 'Adler and Allan Company Information',
					'desc' => 'Please enter your information below',
					'type' => 'title',
					'id'   => $prefix . 'adler_information'
				),
				array(
					'name'    => 'Unique Employee Number',
					'desc'    => '',
					'default' => '',
					'id'      => $prefix . 'employee_number',
					'type'    => 'text'
				),
				array(
					'name'    => 'GMEE Record ID',
					'desc'    => '',
					'default' => '',
					'id'      => $prefix . 'gmee_number',
					'type'    => 'text'
				),
				array(
					'name'    => 'Depot',
					'desc'    => '',
					'default' => '',
					'id'      => $prefix . 'depot',
					'type' => 'select',
					'options' => $depot,
				),
				array(
					'name'    => 'Divison',
					'desc'    => '',
					'default' => '',
					'id'      => $prefix . 'divison',
					'type'    => 'text'
				),
				array(
					'name'    => 'Group Email',
					'desc'    => '',
					'default' => '',
					'id'      => $prefix . 'group_email',
					'type'    => 'text_email'
				),

			),
	);

	// Add other metaboxes as needed

	return $meta_boxes;
}
```

**Comment by katielacy** [comment]
Thank you very much for your quick reply! I am sorry to be a pain but still no luck.... 

Which version of Wordpress are you using?

**Comment by jtsternberg** [comment]
Can you post your entire code? I'm using the latest release of WordPress, but that shouldn't matter.

**Comment by katielacy** [comment]
Good Morning, 

I used the above code for my other CMB metaboxes loops and it fixed the problem! 

Thanks so much for your help sorry to be such a nunsense :+1:
